<a href="https://colab.research.google.com/github/Kalaikujji/kalai/blob/main/pytorch%20basis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
torch.rand(3,2)

tensor([[0.8292, 0.9272],
        [0.1849, 0.8364],
        [0.5264, 0.5987]])

In [4]:
x=torch.empty(4)
print(x)

tensor([-1.7557e-38,  3.1187e-41, -1.7552e-38,  3.1187e-41])


In [5]:
x=torch.empty(2,3)
print(x)

tensor([[-1.7556e-38,  3.1187e-41,         nan],
        [ 3.1187e-41, -1.1796e-07,  4.3726e-41]])


In [6]:
torch.empty(2,3,3)

tensor([[[-2.1577e-38,  3.1187e-41, -8.5403e-17],
         [ 4.3728e-41,  8.9683e-44,  0.0000e+00],
         [ 1.1210e-43,  0.0000e+00,  8.7726e-29]],

        [[ 3.1194e-41,  6.6288e-10,  1.2541e+16],
         [ 2.1707e-18,  7.0952e+22,  1.7748e+28],
         [ 1.8176e+31,  7.2708e+31,  5.0778e+31]]])

In [8]:
torch.empty(2,2,3,4)

tensor([[[[-2.3380e-38,  3.1187e-41,  2.9848e-43,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  2.3694e-38,  1.8788e+31,  1.7220e+22]],

         [[ 2.1715e-18,  6.6715e-10,  6.5928e-10,  6.7062e+22],
          [ 3.3237e+21,  5.1116e+22,  1.2915e-11,  3.2774e-09],
          [ 1.0860e-05,  1.0395e+21,  2.1707e-18,  4.5447e+30]]],


        [[[ 7.0062e+22,  2.1715e-18,  4.5447e+30,  7.0062e+22],
          [ 2.1707e-18,  1.9284e+31,  3.2314e-18,  6.0397e-07],
          [ 4.1300e-08,  1.2915e-11,  5.2301e+22,  2.6369e-09]],

         [[ 1.3165e-08,  6.3081e-10,  2.6514e-09,  1.7472e-04],
          [ 3.0519e-18,  3.1360e+27,  7.0800e+31,  3.1095e-18],
          [ 4.7851e+22,  2.8826e+32,  4.4248e+30,  7.2442e+22]]]])

In [11]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [12]:
x=torch.ones(2,2)

In [13]:
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [14]:
x.size()

torch.Size([2, 2])

In [16]:
x.ndim

2

In [17]:
x=torch.ones(3,3,dtype=torch.int)

In [18]:
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [20]:
torch.tensor([4.3,2,4,5,6])

tensor([4.3000, 2.0000, 4.0000, 5.0000, 6.0000])

In [22]:
torch.manual_seed(42)
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y
      )

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])


In [24]:
z=x+y
print(z)

tensor([[1.2727, 1.5159],
        [0.6394, 1.7529]])


In [25]:
torch.add(x,y)


tensor([[1.2727, 1.5159],
        [0.6394, 1.7529]])

In [26]:
z=x-y
print(z)

tensor([[0.4918, 0.3141],
        [0.1263, 0.1657]])


In [27]:
torch.sub(x,y)


tensor([[0.4918, 0.3141],
        [0.1263, 0.1657]])

In [28]:
torch.mul(x,y)

tensor([[0.3445, 0.5498],
        [0.0982, 0.7613]])

In [29]:
y.add_(x)

tensor([[1.2727, 1.5159],
        [0.6394, 1.7529]])

In [32]:
x=torch.rand(5,3)
print(x)

tensor([[0.5547, 0.3423, 0.6343],
        [0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952],
        [0.0050, 0.3068, 0.1165]])


In [35]:
x[:,2]

tensor([0.6343, 0.9464, 0.7886, 0.1952, 0.1165])

In [37]:
x=torch.rand(1)
x.item()

0.9102694392204285

In [41]:
x=torch.rand(4,4)
print(x)
x.view(16)

tensor([[0.4340, 0.1371, 0.5117, 0.1585],
        [0.0758, 0.2247, 0.0624, 0.1816],
        [0.9998, 0.5944, 0.6541, 0.0337],
        [0.1716, 0.3336, 0.5782, 0.0600]])


tensor([0.4340, 0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816, 0.9998,
        0.5944, 0.6541, 0.0337, 0.1716, 0.3336, 0.5782, 0.0600])

In [42]:
x.view(2,2,4)

tensor([[[0.4340, 0.1371, 0.5117, 0.1585],
         [0.0758, 0.2247, 0.0624, 0.1816]],

        [[0.9998, 0.5944, 0.6541, 0.0337],
         [0.1716, 0.3336, 0.5782, 0.0600]]])

In [50]:
#tensor to numpy array
x=torch.ones(8)
print(x)
print(type(x))
y=x.numpy()
print(y)
print(type(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [52]:
x.add(3)
print(x)

tensor([1., 1., 1., 1., 1., 1., 1., 1.])


In [53]:
print(y)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [55]:
#numpy array to tensor
import numpy as np
a=np.ones(5)
print(a)
print(type(a))
b=torch.from_numpy(a)


[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
